[commands]
reboot = [ "systemctl", "reboot" ]
poweroff = [ "systemctl", "poweroff" ]

[background]
path = "/etc/greetd/background.png"

[GTK]
application_prefer_dark_theme = true

[appearance]
greeting_msg = "Welcome to Hyprland!"
